//
// Created by Rqg on 2018/11/12.
//

#ifndef ENVPROXY_REQCONFIG_H
#define ENVPROXY_REQCONFIG_H


const char REQ_CONFIG[] = "# OpenSSL root CA configuration file.\n"
                         "# Copy to `/root/ca/openssl.cnf`.\n"
                         "\n"
                         "[ ca ]\n"
                         "# `man ca`\n"
                         "default_ca = CA_default\n"
                         "\n"
                         "[ CA_default ]\n"
                         "# Directory and file locations.\n"
                         "dir               = /root/ca\n"
                         "certs             = $dir/certs\n"
                         "crl_dir           = $dir/crl\n"
                         "new_certs_dir     = $dir/newcerts\n"
                         "database          = $dir/index.txt\n"
                         "serial            = $dir/serial\n"
                         "RANDFILE          = $dir/private/.rand\n"
                         "\n"
                         "# The root key and root certificate.\n"
                         "private_key       = $dir/private/ca.key.pem\n"
                         "certificate       = $dir/certs/ca.cert.pem\n"
                         "\n"
                         "# For certificate revocation lists.\n"
                         "crlnumber         = $dir/crlnumber\n"
                         "crl               = $dir/crl/ca.crl.pem\n"
                         "crl_extensions    = crl_ext\n"
                         "default_crl_days  = 30\n"
                         "\n"
                         "# SHA-1 is deprecated, so use SHA-2 instead.\n"
                         "default_md        = sha256\n"
                         "\n"
                         "name_opt          = ca_default\n"
                         "cert_opt          = ca_default\n"
                         "default_days      = 375\n"
                         "preserve          = no\n"
                         "policy            = policy_strict\n"
                         "\n"
                         "[ policy_strict ]\n"
                         "# The root CA should only sign intermediate certificates that match.\n"
                         "# See the POLICY FORMAT section of `man ca`.\n"
                         "countryName             = match\n"
                         "stateOrProvinceName     = match\n"
                         "organizationName        = match\n"
                         "organizationalUnitName  = optional\n"
                         "commonName              = supplied\n"
                         "emailAddress            = optional\n"
                         "\n"
                         "[ policy_loose ]\n"
                         "# Allow the intermediate CA to sign a more diverse range of certificates.\n"
                         "# See the POLICY FORMAT section of the `ca` man page.\n"
                         "countryName             = optional\n"
                         "stateOrProvinceName     = optional\n"
                         "localityName            = optional\n"
                         "organizationName        = optional\n"
                         "organizationalUnitName  = optional\n"
                         "commonName              = supplied\n"
                         "emailAddress            = optional\n"
                         "\n"
                         "[ req ]\n"
                         "# Options for the `req` tool (`man req`).\n"
                         "default_bits        = 2048\n"
                         "distinguished_name  = req_distinguished_name\n"
                         "string_mask         = utf8only\n"
                         "\n"
                         "# SHA-1 is deprecated, so use SHA-2 instead.\n"
                         "default_md          = sha256\n"
                         "\n"
                         "# Extension to add when the -x509 option is used.\n"
                         "x509_extensions     = v3_ca\n"
                         "\n"
                         "[ req_distinguished_name ]\n"
                         "# See <https://en.wikipedia.org/wiki/Certificate_signing_request>.\n"
                         "countryName                     = Country Name (2 letter code)\n"
                         "stateOrProvinceName             = State or Province Name\n"
                         "localityName                    = Locality Name\n"
                         "0.organizationName              = Organization Name\n"
                         "organizationalUnitName          = Organizational Unit Name\n"
                         "commonName                      = Common Name\n"
                         "emailAddress                    = Email Address\n"
                         "\n"
                         "# Optionally, specify some defaults.\n"
                         "countryName_default             = GB\n"
                         "stateOrProvinceName_default     = England\n"
                         "localityName_default            =\n"
                         "0.organizationName_default      = Alice Ltd\n"
                         "organizationalUnitName_default  =\n"
                         "emailAddress_default            =\n"
                         "\n"
                         "[ v3_ca ]\n"
                         "# Extensions for a typical CA (`man x509v3_config`).\n"
                         "subjectKeyIdentifier = hash\n"
                         "authorityKeyIdentifier = keyid:always,issuer\n"
                         "basicConstraints = critical, CA:true\n"
                         "keyUsage = critical, digitalSignature, cRLSign, keyCertSign\n"
                         "\n"
                         "[ v3_intermediate_ca ]\n"
                         "# Extensions for a typical intermediate CA (`man x509v3_config`).\n"
                         "subjectKeyIdentifier = hash\n"
                         "authorityKeyIdentifier = keyid:always,issuer\n"
                         "basicConstraints = critical, CA:true, pathlen:0\n"
                         "keyUsage = critical, digitalSignature, cRLSign, keyCertSign\n"
                         "\n"
                         "[ usr_cert ]\n"
                         "# Extensions for client certificates (`man x509v3_config`).\n"
                         "basicConstraints = CA:FALSE\n"
                         "nsCertType = client, email\n"
                         "nsComment = \"OpenSSL Generated Client Certificate\"\n"
                         "subjectKeyIdentifier = hash\n"
                         "authorityKeyIdentifier = keyid,issuer\n"
                         "keyUsage = critical, nonRepudiation, digitalSignature, keyEncipherment\n"
                         "extendedKeyUsage = clientAuth, emailProtection\n"
                         "\n"
                         "[ server_cert ]\n"
                         "# Extensions for server certificates (`man x509v3_config`).\n"
                         "basicConstraints = CA:FALSE\n"
                         "nsCertType = server\n"
                         "nsComment = \"OpenSSL Generated Server Certificate\"\n"
                         "subjectKeyIdentifier = hash\n"
                         "authorityKeyIdentifier = keyid,issuer:always\n"
                         "keyUsage = critical, digitalSignature, keyEncipherment\n"
                         "extendedKeyUsage = serverAuth\n"
                         "\n"
                         "[ crl_ext ]\n"
                         "# Extension for CRLs (`man x509v3_config`).\n"
                         "authorityKeyIdentifier=keyid:always\n"
                         "\n"
                         "[ ocsp ]\n"
                         "# Extension for OCSP signing certificates (`man ocsp`).\n"
                         "basicConstraints = CA:FALSE\n"
                         "subjectKeyIdentifier = hash\n"
                         "authorityKeyIdentifier = keyid,issuer\n"
                         "keyUsage = critical, digitalSignature\n"
                         "extendedKeyUsage = critical, OCSPSigning";

#endif //ENVPROXY_REQCONFIG_H
